name: Build and Release

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up C++ environment
        run: sudo apt-get install -y g++ cmake
      
      - name: Find and build C++ projects
        run: |
          mkdir -p build-output/cpp
          # 프로젝트 구조 확인
          find . -name "CMakeLists.txt" -type f | while read -r cmake_file; do
            dir=$(dirname "$cmake_file")
            echo "Building C++ project in $dir"
            mkdir -p "$dir/build"
            cd "$dir/build"
            cmake ..
            cmake --build .
            # 실행 파일 찾아서 복사
            find . -type f -executable -not -path "*/\.*" -exec cp {} ../../build-output/cpp/ \;
            cd -
          done
      
      - name: Upload C++ artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cpp-builds
          path: build-output/cpp
          if-no-files-found: warn

  build-csharp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      
      - name: Find and build C# projects
        run: |
          mkdir -p build-output/csharp
          # .csproj 파일 찾아서 빌드
          find . -name "*.csproj" -type f | while read -r csproj_file; do
            dir=$(dirname "$csproj_file")
            echo "Building C# project: $csproj_file"
            dotnet restore "$csproj_file"
            dotnet build "$csproj_file" --configuration Release
            # 빌드 결과물 복사
            find "$dir/bin" -name "*.dll" -o -name "*.exe" 2>/dev/null | xargs -I{} cp {} build-output/csharp/ 2>/dev/null || true
          done
      
      - name: Upload C# artifacts
        uses: actions/upload-artifact@v3
        with:
          name: csharp-builds
          path: build-output/csharp
          if-no-files-found: warn

  build-kotlin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Find and build Kotlin projects
        run: |
          mkdir -p build-output/kotlin
          # build.gradle 또는 build.gradle.kts 파일 찾기
          find . -name "build.gradle*" -type f | while read -r gradle_file; do
            dir=$(dirname "$gradle_file")
            echo "Building Kotlin project in $dir"
            if [ -f "$dir/gradlew" ]; then
              cd "$dir"
              chmod +x ./gradlew
              ./gradlew build
              cd -
            else
              cd "$dir"
              gradle build
              cd -
            fi
            # JAR 파일 복사
            find "$dir" -name "*.jar" -not -path "*/\.*" | xargs -I{} cp {} build-output/kotlin/ 2>/dev/null || true
          done
      
      - name: Upload Kotlin artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kotlin-builds
          path: build-output/kotlin
          if-no-files-found: warn

  create-release:
    needs: [build-cpp, build-csharp, build-kotlin]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Create output directory
        run: mkdir -p combined-builds/{cpp,csharp,kotlin}
      
      - name: Download C++ artifacts
        uses: actions/download-artifact@v3
        with:
          name: cpp-builds
          path: combined-builds/cpp
        continue-on-error: true
      
      - name: Download C# artifacts
        uses: actions/download-artifact@v3
        with:
          name: csharp-builds
          path: combined-builds/csharp
        continue-on-error: true
      
      - name: Download Kotlin artifacts
        uses: actions/download-artifact@v3
        with:
          name: kotlin-builds
          path: combined-builds/kotlin
        continue-on-error: true
      
      - name: Check directory contents
        run: |
          echo "Contents of combined-builds:"
          ls -la combined-builds
          echo "Contents of cpp directory:"
          ls -la combined-builds/cpp || echo "No C++ builds"
          echo "Contents of csharp directory:"
          ls -la combined-builds/csharp || echo "No C# builds"
          echo "Contents of kotlin directory:"
          ls -la combined-builds/kotlin || echo "No Kotlin builds"
      
      - name: Create archive
        run: |
          cd combined-builds
          zip -r design-patterns-implementations.zip .
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: combined-builds/design-patterns-implementations.zip
          name: Design Patterns Build ${{ github.sha }}
          tag_name: build-${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}