name: Simple Build and Release

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create directory structure
        run: mkdir -p builds/{cpp,csharp,kotlin}
      
      - name: Create placeholder files
        run: |
          echo "C++ build output" > builds/cpp/cpp-output.txt
          echo "C# build output" > builds/csharp/csharp-output.txt
          echo "Kotlin build output" > builds/kotlin/kotlin-output.txt
      
      - name: Create zip file
        run: |
          cd builds
          zip -r ../design-patterns-builds.zip .
      
      - name: Create Release
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "design-patterns-builds.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.run_number }}
          name: Design Patterns Build ${{ github.run_number }}