name: Simple Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create directory structure
        run: mkdir -p builds/{cpp,csharp,kotlin}
      
      - name: Create placeholder files
        run: |
          echo "C++ build output" > builds/cpp/cpp-output.txt
          echo "C# build output" > builds/csharp/csharp-output.txt
          echo "Kotlin build output" > builds/kotlin/kotlin-output.txt
      
      - name: Create zip file
        run: |
          cd builds
          zip -r ../design-patterns-builds.zip .
      
      - name: List created files
        run: |
          ls -la
          ls -la builds/