name: Compile Projects

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-cpp:
    name: Build C++ Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up C++ environment
        run: sudo apt-get install -y g++ cmake
      
      - name: Build C++ projects
        run: |
          cd cpp  # C++ 프로젝트 디렉토리로 이동 (경로는 프로젝트에 맞게 조정)
          mkdir -p build
          cd build
          cmake ..
          cmake --build .
      
      - name: Run tests (if available)
        run: |
          cd cpp/build
          ctest --output-on-failure
        continue-on-error: true

  build-csharp:
    name: Build C# Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      
      - name: Restore dependencies
        run: |
          cd csharp  # C# 프로젝트 디렉토리로 이동 (경로는 프로젝트에 맞게 조정)
          dotnet restore
      
      - name: Build C# projects
        run: |
          cd csharp
          dotnet build --no-restore --configuration Release
      
      - name: Run tests (if available)
        run: |
          cd csharp
          dotnet test --no-build --verbosity normal
        continue-on-error: true

  build-kotlin:
    name: Build Kotlin Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Build Kotlin projects
        run: |
          cd kotlin  # Kotlin 프로젝트 디렉토리로 이동 (경로는 프로젝트에 맞게 조정)
          ./gradlew build
      
      - name: Run tests (if available)
        run: |
          cd kotlin
          ./gradlew test
        continue-on-error: true