name: Compress and Release

on:
  push:
    branches:
      - master  # master 브랜치에 push될 때마다 실행

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu 환경에서 실행
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # GitHub 리포지토리에서 코드 가져오기

      - name: Build your project
        run: |
          # 여기에 컴파일 명령어를 넣어주세요
          echo "Building project..."

      - name: Compress build files
        run: |
          # 빌드된 파일을 압축
          tar -czf build.tar.gz ./build  # ./build 폴더를 압축

      - name: Upload Release Assets
        uses: gh-actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build.tar.gz
          asset_name: build.tar.gz
          asset_content_type: application/gzip

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build.tar.gz
