name: Build and Release

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# 명시적 권한 설정
permissions:
  contents: write
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create directory structure
        run: mkdir -p builds/{cpp,csharp,kotlin}
      
      - name: Create placeholder files
        run: |
          echo "C++ build output" > builds/cpp/cpp-output.txt
          echo "C# build output" > builds/csharp/csharp-output.txt
          echo "Kotlin build output" > builds/kotlin/kotlin-output.txt
      
      - name: Create zip file
        run: |
          cd builds
          zip -r ../design-patterns-builds.zip .
      
      # 디버깅 정보 추가
      - name: Debug info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Is it a push to main/master? ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}"
      
      # 릴리즈 생성
      - name: Create Release
        if: github.event_name == 'push'  # 조건을 단순화
        uses: softprops/action-gh-release@v1
        with:
          files: design-patterns-builds.zip
          tag_name: v${{ github.run_number }}
          name: Design Patterns Build ${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false